---
- name: Create project for ACME Controller
  openshift_project:
    name: "{{ appuio_openshift_acme_namespace }}"

- name: Create temp directory for doing work in
  command: mktemp -d /tmp/ansible-acme-XXXXXXXX
  register: mktemp
  changed_when: False

- set_fact:
    tempdir: "{{ mktemp.stdout }}"

- name: Copy template
  copy:
    src: "{{ role_path }}/files/acme-controller-template.yml"
    dest: "{{ tempdir }}/template.yml"
  changed_when: False

- name: Instantiate ACME Controller template
  vars:
    acmeurl: "{{ appuio_openshift_acme_endpoint_alias[appuio_openshift_acme_endpoint] | default(appuio_openshift_acme_endpoint) }}"
  openshift_resource:
    namespace: "{{ appuio_openshift_acme_namespace }}"
    template: "{{ tempdir }}/template.yml"
    arguments:
      OPENSHIFT_ACME_ACMEURL: "{{ acmeurl | mandatory }}"
      OPENSHIFT_ACME_LOGLEVEL: "{{ appuio_openshift_acme_loglevel }}"
      DOCKER_IMAGE: "{{ appuio_openshift_acme_docker_image | mandatory }}"
      DOCKER_IMAGE_TAG: "{{ appuio_openshift_acme_docker_image_tag | mandatory }}"
      EXPOSER_IMAGE: "{{ appuio_openshift_acme_exposer_image | mandatory }}"
      EXPOSER_IMAGE_TAG: "{{ appuio_openshift_acme_exposer_image_tag | mandatory }}"
      HTTP_PROXY: "{{ appuio_openshift_acme_http_proxy | default(omit) }}"
      NO_PROXY: "{{ appuio_openshift_acme_no_proxy | default(omit) }}"
      RSA_KEY_BIT_SIZE: "{{ appuio_openshift_acme_default_rsa_key_bit_size | mandatory }}"
      CONTROLLER_CPU_REQUESTS: "{{ appuio_openshift_acme_controller_cpu_requests | mandatory }}"
      CONTROLLER_CPU_LIMIITS: "{{ appuio_openshift_acme_controller_cpu_limits | mandatory }}"
      CONTROLLER_MEMORY_REQUESTS: "{{ appuio_openshift_acme_controller_memory_requests | mandatory }}"
      CONTROLLER_MEMORY_LIMITS: "{{ appuio_openshift_acme_controller_memory_limits | mandatory }}"

- name: Delete temp directory
  file:
    name: "{{ tempdir }}"
    state: absent
  changed_when: False

- name: Cluster role assignement
  openshift_policy:
    cluster_roles:
    - acme-controller
    users:
    - "system:serviceaccount:{{ appuio_openshift_acme_namespace }}:acme-controller"
