apiVersion: v1
kind: Template
metadata:
  name: acme-controller
parameters:
- description: ACME Endpoint URL
  name: OPENSHIFT_ACME_ACMEURL
- description: Controller loglevel
  name: OPENSHIFT_ACME_LOGLEVEL
- description: Docker Image of ACME controller
  name: DOCKER_IMAGE
- description: Docker Image Tag of ACME controller
  name: DOCKER_IMAGE_TAG
- description: Docker Image of ACME challenge exposer
  name: EXPOSER_IMAGE
- description: Docker Image Tag of ACME challenge exposer
  name: EXPOSER_IMAGE_TAG
objects:
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: acme-controller
    labels:
      app: acme-controller
  rules:
  - apiGroups:
    - "route.openshift.io"
    resources:
    - routes
    - routes/finalizers
    verbs:
    - create
    - get
    - list
    - watch
    - update
    - patch
    - delete
    - deletecollection
  - apiGroups:
    - "route.openshift.io"
    resources:
    - routes/custom-host
    verbs:
    - create
  - apiGroups:
    - ""
    resources:
    - configmaps
    - services
    - secrets
    verbs:
    - create
    - get
    - list
    - watch
    - update
    - patch
    - delete
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - update
    - patch
  - apiGroups:
    - ""
    resources:
    - limitranges
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - "apps"
    resources:
    - replicasets
    verbs:
    - create
    - get
    - list
    - watch
    - update
    - patch
    - delete
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: letsencrypt-issuer
    annotations:
      "acme.openshift.io/priority": "100"
    labels:
      managed-by: "openshift-acme"
      type: "CertIssuer"
  data:
    "cert-issuer.types.acme.openshift.io": |
      {
        "type": "ACME",
        "acmeCertIssuer": {
          "directoryUrl": "${OPENSHIFT_ACME_ACMEURL}"
        }
      }
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: acme-controller
    labels:
      app: acme-controller
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: acme-controller
    labels:
      app: acme-controller
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: ${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG}
      from:
        kind: DockerImage
        name: ${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG}
      importPolicy:
        scheduled: true
      name: ${DOCKER_IMAGE_TAG}
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: acme-controller
    name: acme-controller
  spec:
    replicas: 1
    selector:
      app: acme-controller
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: acme-controller
      spec:
        containers:
        - name: acme-controller
          image: acme-controller:${DOCKER_IMAGE_TAG}
          imagePullPolicy: Always
          args:
          - --exposer-image=${EXPOSER_IMAGE}:${EXPOSER_IMAGE_TAG}
          - --loglevel=${OPENSHIFT_ACME_LOGLEVEL}
          resources:
            limits:
              cpu: '500m'
              memory: '512Mi'
            requests:
              cpu: '500m'
              memory: '512Mi'
        serviceAccountName: acme-controller
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - acme-controller
        from:
          kind: ImageStreamTag
          name: acme-controller:${DOCKER_IMAGE_TAG}
    - type: ConfigChange
